### ISSUE TITLE
How To Run

### ISSUE THREAD

**Issue by berandakreatif** [Gielert/NoodleJS#16]
Hello, 

I just want to testing this project with my private murmur server and i have some question to ask :

1. How to run this project for testing?

i was install npm using "npm install" and then i use command "npm start or npm run" but not running, please advice 

Thx

**Comment by kripton** [comment]
NoodleJS is a library that you need to use in your own NodeJS program. See the example in the Readme file:  https://github.com/Gielert/NoodleJS#example-usage

**Comment by Gielert** [comment]
Like @kripton said. If you have any additional questions feel free to ask.
