### ISSUE TITLE
Receive Audio..

### ISSUE THREAD

**Issue by vanvanni** [Gielert/NoodleJS#17]
I see you can send audio but can we also receive audio and if so in what codec?

**Comment by Gielert** [comment]
Receiving audio hasn't been implemented yet. The codec used by mumble is opus. I'm pretty tied up with work a.t.m., perhaps you could see if you can implement it. Otherwise, I'll need to check once I have time again :)

**Comment by vanvanni** [comment]
@Gielert Not really into that and good enough for it. Also completely new to Mumble. But I can give it a little shot

**Comment by kripton** [comment]
See #30 ;)

**Comment by vanvanni** [comment]
@kripton Seems great, does mumble only support opus? I hope this get merged 😊

**Comment by Gielert** [comment]
Mumble supports another codec called `Celt`. But Opus is widely used in voip applications. For now this library only supports sending and receiving Opus data.

**Comment by kripton** [comment]
Indeed, Celt and Speex are two more codecs that have been used in Mumble in the past. However, if you use the latest clients and servers (1.3.x), it should only be Opus everywhere. And the current audio sending code supports Opus as the only codec, so I didn't want to introduce any more dependencies.

**Comment by Gielert** [comment]
Fixed with #30
