### ISSUE TITLE
stream.end does not trigger correctly?

### ISSUE THREAD

**Issue by lolcatw** [Gielert/NoodleJS#55]
Hello!

If I pipe a opus stream inside `client.voiceConnection.playStream`, the following happens:
1) File is sent
2) about 3/4th of the way, the `end` event is triggered

example:
```
fs = include("fs");

var filehandle = fs.createReadStream("myfile.opus");
client.voiceConnection.playStream(filehandle);
file.on("end", function(){ console.log("fuck"); });
```
This usually happens when piping files longer than 30 seconds. Is this due to the fact that noodle.js sent the file already, even though the stream is still being heard? If so, would there be a way to add an event for when a stream is done playing?

Right now, my workaround is to just probe the file for duration and create a timeout for when its done playing, but I think adding this function inside the library would be great

This library is great, thanks

**Comment by Gielert** [comment]
Hi!

The `file.on('end')` finishes once the file has been read. Not when the stream has been written to mumble. Instead you need to subscribe on the `client.voiceConnection.on('end')` event. An example can be found [on line 202](https://github.com/Gielert/NoodleJS/blob/master/test/test.js#L202) in the tests. Let me know of that worked ;)

**Comment by lolcatw** [comment]
Interesting! Everything works on my end now. I wish you a good night, its 4AM now lol. This ends my day well!!
